CREATE TABLE USER(


   USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    SURNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    PESEL DOUBLE (250) NOT NULL
);


INSERT INTO USER (name, surname, email, password, pesel) VALUES
('Gerard', 'Burgues', 'gerard@gmail.com', '123', 00000);

CREATE TABLE DEPARTMENT(
                           DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY ,
                           NAME VARCHAR(150)

);
CREATE TABLE PROFESSOR(
    USER_ID INT,
    PROFESSOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES  USER (USER_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)


);

CREATE TABLE STUDENT(

    USER_ID INT,
    INDEX_NO INT,
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);
CREATE TABLE COURSE(
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150),
    DESCRIPTION VARCHAR(500),
    PROFESSOR_ID INT,
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (PROFESSOR_ID)
);

CREATE TABLE TEST(
    TEST_ID INT AUTO_INCREMENT PRIMARY KEY,
    STARTDATE DATE,
    STARTTIME TIMESTAMP,
    DURATIONMINUTES INT,
    COURSE_ID INT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)

);


CREATE TABLE QUESTION(
    QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY ,
    QUESTIONTYPE_ID INT,
    TEST_ID INT,
    FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID),
    FOREIGN KEY (QUESTIONTYPE_ID) REFERENCES QUESTIONTYPE_ENUM(QUESTIONTYPE_ID)

);
CREATE TABLE QUESTIONTYPE_ENUM(

    QUESTIONTYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE ANSWER(
    ANSWER_ID INT AUTO_INCREMENT PRIMARY KEY ,
    VALUE VARCHAR(100),
    ISCORRECT BIT,
    QUESTION_ID INT,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID)

);

CREATE TABLE STUDENTTEST(
    STUDENTEST_ID INT AUTO_INCREMENT PRIMARY KEY ,
    MARK DOUBLE,
    TEST_ID INT,
    STUDENT_ID INT,
    FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID),
    FOREIGN KEY  (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)

);

CREATE TABLE STUDENTCOURSE(
    STUDENTCOURSE_ID INT AUTO_INCREMENT PRIMARY KEY ,
    FINALGRADE DOUBLE,
    COURSE_ID INT,
    STUDENT_ID INT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)

);
CREATE TABLE STUDENTDEPARTMENT (
    STUDENTSDEPARMENT_ID INT AUTO_INCREMENT PRIMARY KEY ,
    DEPARMENT_ID INT,
    STUDENT_ID INT,
    FOREIGN KEY (DEPARMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
)